# Build the App!
- name: Build Tauri App
  uses: tauri-apps/tauri-action@v0
  env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  with:
      tagName: ${{ github.ref_name }}
      releaseName: "ClipDude v__VERSION__"
      releaseBody: "New release of ClipDude."
      releaseDraft: false
      prerelease: false
